# Generated by Django 4.2.4 on 2023-09-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagControle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('duracaoDias', models.IntegerField()),
                ('frequencia', models.IntegerField()),
            ],
        ),
    ]
