# Generated by Django 4.2.4 on 2023-09-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagControle', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagControle.plano'),
        ),
    ]
